/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainlibrary;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @ProgramName bookish
 */
public class ReserveProgram extends javax.swing.JFrame {
   
   public static int currentRow;
    /**
     * Creates new form ViewToy
     * @throws java.sql.SQLException
     */
    public ReserveProgram() throws SQLException {
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        initComponents();
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
       // String Data[][]=null;
      //  String Column[]=null;
        try(Connection Con = DB.getConnection()) {
            PreparedStatement ps=Con.prepareStatement("select programlist.ProgramNum, programlist.LibraryName, programlist.ProgramName, programlist.Day, programlist.Time, programlist.Age, programlist.Max, programlist.Place from programlist",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs= ps.executeQuery();
            
           ResultSetMetaData rsmd = rs.getMetaData();
  
            int colnum=rsmd.getColumnCount();
        
            
           
            String Row[];
            String Check="";
            Row = new String[colnum];
            while(rs.next()){
                for(int i=1;i<=colnum;i++){
                 
                    Row[i-1]=rs.getString(i);
                    }
                 model.addRow(Row);
                  
            }
   
                    //count++;
               
            
           Con.close();
        }catch(Exception e){System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NameRadio = new javax.swing.JRadioButton();
        DayRadio = new javax.swing.JRadioButton();
        ALL = new javax.swing.JRadioButton();
        SearchField = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        ShowALL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {   //테이블 헤더 부분
                "프로그램 번호", "장난감 도서관 이름", "프로그램 이름", "요일", "시간", "나이", "정원", "장소"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
               jTable1MouseClicked(e);
            }
        });
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("프로그램");

        jButton1.setText("종료");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NameRadio.setText("이름");
        NameRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameRadioActionPerformed(evt);
            }
        });

        DayRadio.setText("요일");
        DayRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayRadioActionPerformed(evt);
            }
        });

        ALL.setText("전체");
        ALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALLActionPerformed(evt);
            }
        });


        Search.setText("찾기");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        ShowALL.setText("전체 보기");
        ShowALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowALLActionPerformed(evt);
            }
        });

        setTitle("프로그램 예약");
        setResizable(false); //pch : 창 크기 고정
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
           layout.createParallelGroup(Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                 .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                       .addGap(698)
                       .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                       .addGap(25)
                       .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1464, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                       .addGap(452)
                       .addComponent(NameRadio)
                       .addGap(30)
                       .addComponent(DayRadio)
                       .addGap(308)
                       .addComponent(ALL))
                    .addGroup(layout.createSequentialGroup()
                       .addGap(725)
                       .addComponent(jLabel1)))
                 .addContainerGap(29, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                 .addGap(0, 688, Short.MAX_VALUE)
                 .addComponent(ShowALL)
                 .addGap(122)
                 .addComponent(SearchField, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
                 .addGap(36)
                 .addComponent(Search)
                 .addGap(288))
        );
        layout.setVerticalGroup(
           layout.createParallelGroup(Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                 .addGap(34)
                 .addComponent(jLabel1)
                 .addGap(18)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(NameRadio)
                    .addComponent(DayRadio)
                    .addComponent(ALL))
                 .addGap(16)
                 .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                    .addComponent(SearchField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(ShowALL))
                 .addPreferredGap(ComponentPlacement.UNRELATED)
                 .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                 .addPreferredGap(ComponentPlacement.UNRELATED)
                 .addComponent(jButton1)
                 .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jTable1MouseClicked(java.awt.event.MouseEvent e)
    {
       if(e.getClickCount()==2)   //더블클릭하면
       {
           currentRow = jTable1.getSelectedRow();   //선택한 행 번호 저장
           System.out.println("current row = "+currentRow);
           if(TransProgramDao.checkMax())   //MAX Current 값 비교
           {   
              JOptionPane.showMessageDialog(ReserveProgram.this, "이미 다 찼습니다.! ","예약 에러!", JOptionPane.ERROR_MESSAGE); 
             
           }
            else
            {
                   
                this.dispose();
               IssuedProgram.main(new String[]{});
            }
               
 
       
  
       }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code hereset
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        if(SearchField.getText()=="")
      JOptionPane.showMessageDialog(ReserveProgram.this, "찾을 목록이 없습니다","찾기 에러!", JOptionPane.ERROR_MESSAGE);

        if(!ALL.isSelected())
           // if(!NotIssued.isSelected())
            ALL.setEnabled(true);
        
        int flag=0;
        if(ALL.isSelected())
            flag=0;
      //  if(NotIssued.isSelected())
       //     flag=1;
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        while(model.getRowCount()>0)
            model.removeRow(model.getRowCount()-1);
        if(NameRadio.isSelected())
        {
            String Search = "%"+SearchField.getText()+"%";
        try(Connection Con = DB.getConnection()) {
            PreparedStatement ps=Con.prepareStatement("select programlist.ProgramNum, programlist.LibraryName, programlist.ProgramName, programlist.Day, programlist.Time, programlist.Age, programlist.Max, programlist.Place from programlist where ProgramName like ?", ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, Search);
            ResultSet rs= ps.executeQuery();
            
           ResultSetMetaData rsmd = rs.getMetaData();
  
            int colnum=rsmd.getColumnCount();
            
            String Row[];
            String Check="";
            Row = new String[colnum];
            while(rs.next()){
                for(int i=1;i<=colnum;i++){
                 
                    Row[i-1]=rs.getString(i);
                    }
                 model.addRow(Row);
                  
            }
            
            int rowcount = model.getRowCount();
             System.out.println(rowcount);
            if(rowcount==0)
            {
                String NoRow[];
                NoRow = new String[7];
                NoRow[3]="NO";
                NoRow[4]="RESULT";
                NoRow[0]="";
                NoRow[1]="";
                NoRow[2]="";
                NoRow[5]="";
                NoRow[6]="";
                model.addRow(NoRow);
                
                
            }
   
                    //count++;
               
            
           Con.close();
        }catch(Exception e){System.out.println(e);
    } }
        
        else if(DayRadio.isSelected())
        {
            
            String Search = "%"+SearchField.getText()+"%";
        try(Connection Con = DB.getConnection()) {
            PreparedStatement ps=Con.prepareStatement("select A.ProgramNum, A.LibraryName, A.ProgramName, A.Day, A.Time, A.Age, A.Max, A.Place from (select * from programlist where Day like ?)a",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ps.setString(1, Search);
            ResultSet rs= ps.executeQuery();
            
           ResultSetMetaData rsmd = rs.getMetaData();
  
            int colnum=rsmd.getColumnCount();
            
           

            String Row[];
            String Check="";
            Row = new String[colnum];
            while(rs.next()){
                for(int i=1;i<=colnum;i++){
                 
                    Row[i-1]=rs.getString(i);
                    }
                 model.addRow(Row);
                  
            }
   
                    //count++;
               
            
            int rowcount = model.getRowCount();
             System.out.println(rowcount);
            if(rowcount==0)
            {
                String NoRow[];
                NoRow = new String[7];
                NoRow[3]="NO";
                NoRow[4]="RESULT";
                NoRow[0]="";
                NoRow[1]="";
                NoRow[2]="";
                NoRow[5]="";
                NoRow[6]="";
                model.addRow(NoRow);
                
                
            }
   
                    //count++;
               
            
           Con.close();
        }catch(Exception e){System.out.println(e);
    }
        }
        
        else
        {
            
            JOptionPane.showMessageDialog(ReserveProgram.this, "이름이나 요일을 선택하세요","선택할 수 없습니다!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void DayRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayRadioActionPerformed
        // TODO add your handling code here:
        NameRadio.setSelected(false);
    }//GEN-LAST:event_DayRadioActionPerformed

    private void NameRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameRadioActionPerformed
        // TODO add your handling code here:
        DayRadio.setSelected(false);
    }//GEN-LAST:event_NameRadioActionPerformed

    private void ALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALLActionPerformed
        // TODO add your handling code here:
      //  
        ALL.setSelected(false);
    }//GEN-LAST:event_ALLActionPerformed

   /* private void NotIssuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotIssuedActionPerformed
        // TODO add your handling code here:
        
        NotIssued.setSelected(false);
    }//GEN-LAST:event_NotIssuedActionPerformed
*/
    private void ShowALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowALLActionPerformed
        // TODO add your handling code here:
        DayRadio.setSelected(false);
        NameRadio.setSelected(false);
          DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
         while(model.getRowCount()>0)
            model.removeRow(model.getRowCount()-1);
         
         
         if(!ALL.isSelected()/*&&!NotIssued.isSelected()*/)
         {
             ALL.setSelected(true);
         }
         
         
         int flag=0;
         if(ALL.isSelected())
             flag=0;
        /* if(NotIssued.isSelected())
         */    flag=1;
       // String Data[][]=null;
      //  String Column[]=null;
        try(Connection Con = DB.getConnection()) {
            PreparedStatement ps=Con.prepareStatement("select programlist.ProgramNum, programlist.LibraryName, programlist.ProgramName, programlist.Day, programlist.Time, programlist.Age, programlist.Max, programlist.Place from programlist",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs= ps.executeQuery();
            
           ResultSetMetaData rsmd = rs.getMetaData();
  
            int colnum=rsmd.getColumnCount();
        
            String Row[];
            String Check="";
            Row = new String[colnum];
            while(rs.next()){
                for(int i=1;i<=colnum;i++){
                 
                    Row[i-1]=rs.getString(i);
                    }
                 model.addRow(Row);
                  
            }
   
                    //count++;
               
            
           Con.close();
        }catch(Exception e){System.out.println(e);
    }
    }//GEN-LAST:event_ShowALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReserveProgram().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ReserveProgram.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ALL;
    private javax.swing.JRadioButton DayRadio;
    private javax.swing.JRadioButton NameRadio;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchField;
    private javax.swing.JButton ShowALL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables


}
